[build]
builder = "NIXPACKS"
buildCommand = "cd algorithmic-edge-site-main && npm install && npm run build"

[deploy]
startCommand = "cd algorithmic-edge-site-main && npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "8080" 